import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';
import '../models/task.dart';

class ExportService {
  /// Export tasks to PDF and return the file path
  Future<String> exportToPdf(List<Task> tasks, {String title = 'TaskMaster Pro - Tasks Report'}) async {
    final pdf = pw.Document();
    final now = DateTime.now();

    // Separate active and completed tasks
    final active = tasks.where((t) => !t.isCompleted).toList();
    final completed = tasks.where((t) => t.isCompleted).toList();

    final priorityNames = {1: 'Low', 2: 'Medium', 3: 'High'};

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(title,
                    style: pw.TextStyle(
                        fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text(
                  '${now.day}/${now.month}/${now.year}',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                ),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Divider(thickness: 2, color: PdfColors.deepPurple),
            pw.SizedBox(height: 8),
            pw.Row(
              children: [
                _statBox('Total', '${tasks.length}'),
                pw.SizedBox(width: 16),
                _statBox('Active', '${active.length}'),
                pw.SizedBox(width: 16),
                _statBox('Completed', '${completed.length}'),
                pw.SizedBox(width: 16),
                _statBox('Completion Rate',
                    tasks.isEmpty ? '0%' : '${(completed.length / tasks.length * 100).round()}%'),
              ],
            ),
            pw.SizedBox(height: 16),
          ],
        ),
        build: (context) => [
          // Active tasks
          if (active.isNotEmpty) ...[
            pw.Text('Active Tasks',
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.deepPurple)),
            pw.SizedBox(height: 8),
            ...active.map((task) => _taskRow(task, priorityNames)),
          ],

          if (completed.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text('Completed Tasks',
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.green700)),
            pw.SizedBox(height: 8),
            ...completed.map((task) => _taskRow(task, priorityNames)),
          ],
        ],
        footer: (context) => pw.Column(
          children: [
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by TaskMaster Pro',
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey500)),
                pw.Text('Page ${context.pageNumber}/${context.pagesCount}',
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey500)),
              ],
            ),
          ],
        ),
      ),
    );

    // Save PDF
    final dir = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/taskmaster_report_${now.millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  /// Export tasks to CSV and return the file path
  Future<String> exportToCsv(List<Task> tasks) async {
    final buffer = StringBuffer();
    buffer.writeln('Title,Description,Category,Priority,Status,Due Date,Created');

    for (final task in tasks) {
      final title = _escapeCsv(task.title);
      final desc = _escapeCsv(task.description);
      final status = task.isCompleted ? 'Completed' : 'Active';
      final priority = {1: 'Low', 2: 'Medium', 3: 'High'}[task.priority] ?? 'Medium';
      final dueDate = task.dueDate != null
          ? '${task.dueDate!.day}/${task.dueDate!.month}/${task.dueDate!.year}'
          : '';
      final created =
          '${task.createdAt.day}/${task.createdAt.month}/${task.createdAt.year}';

      buffer.writeln('$title,$desc,${task.category},$priority,$status,$dueDate,$created');
    }

    final dir = await getApplicationDocumentsDirectory();
    final now = DateTime.now();
    final file = File(
        '${dir.path}/taskmaster_export_${now.millisecondsSinceEpoch}.csv');
    await file.writeAsString(buffer.toString());
    return file.path;
  }

  /// Open a file
  Future<void> openFile(String path) async {
    await OpenFilex.open(path);
  }

  pw.Widget _statBox(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        children: [
          pw.Text(value,
              style:
                  pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 2),
          pw.Text(label,
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  pw.Widget _taskRow(Task task, Map<int, String> priorityNames) {
    final priorityColor = {
      1: PdfColors.green,
      2: PdfColors.orange,
      3: PdfColors.red,
    };

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 4,
            height: 30,
            color: priorityColor[task.priority] ?? PdfColors.grey,
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  task.title,
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    decoration: task.isCompleted
                        ? pw.TextDecoration.lineThrough
                        : null,
                  ),
                ),
                if (task.description.isNotEmpty)
                  pw.Text(task.description,
                      style: const pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
                pw.SizedBox(height: 4),
                pw.Row(
                  children: [
                    pw.Text('${task.category}  ',
                        style: const pw.TextStyle(
                            fontSize: 9, color: PdfColors.grey600)),
                    pw.Text('${priorityNames[task.priority]}  ',
                        style: pw.TextStyle(
                            fontSize: 9,
                            color: priorityColor[task.priority] ??
                                PdfColors.grey)),
                    if (task.dueDate != null)
                      pw.Text(
                          'Due: ${task.dueDate!.day}/${task.dueDate!.month}/${task.dueDate!.year}',
                          style: const pw.TextStyle(
                              fontSize: 9, color: PdfColors.grey600)),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _escapeCsv(String value) {
    if (value.contains(',') || value.contains('"') || value.contains('\n')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }
}
