import 'dart:convert';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';
import '../models/category.dart';
import '../models/label.dart';
import '../models/note.dart';
import '../models/project.dart';
import '../models/task.dart';

class ExportService {
  /// Export tasks to PDF and return the file path
  Future<String> exportToPdf(List<Task> tasks, {String title = 'Focus24 - Tasks Report'}) async {
    final pdf = pw.Document();
    final now = DateTime.now();

    // Separate active and completed tasks
    final active = tasks.where((t) => !t.isCompleted).toList();
    final completed = tasks.where((t) => t.isCompleted).toList();

    final priorityNames = {1: 'Low', 2: 'Medium', 3: 'High'};

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(title,
                    style: pw.TextStyle(
                        fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text(
                  '${now.day}/${now.month}/${now.year}',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                ),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Divider(thickness: 2, color: PdfColors.deepPurple),
            pw.SizedBox(height: 8),
            pw.Row(
              children: [
                _statBox('Total', '${tasks.length}'),
                pw.SizedBox(width: 16),
                _statBox('Active', '${active.length}'),
                pw.SizedBox(width: 16),
                _statBox('Completed', '${completed.length}'),
                pw.SizedBox(width: 16),
                _statBox('Completion Rate',
                    tasks.isEmpty ? '0%' : '${(completed.length / tasks.length * 100).round()}%'),
              ],
            ),
            pw.SizedBox(height: 16),
          ],
        ),
        build: (context) => [
          // Active tasks
          if (active.isNotEmpty) ...[
            pw.Text('Active Tasks',
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.deepPurple)),
            pw.SizedBox(height: 8),
            ...active.map((task) => _taskRow(task, priorityNames)),
          ],

          if (completed.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text('Completed Tasks',
                style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.green700)),
            pw.SizedBox(height: 8),
            ...completed.map((task) => _taskRow(task, priorityNames)),
          ],
        ],
        footer: (context) => pw.Column(
          children: [
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by Focus24',
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey500)),
                pw.Text('Page ${context.pageNumber}/${context.pagesCount}',
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey500)),
              ],
            ),
          ],
        ),
      ),
    );

    // Save PDF
    final dir = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/focus24_report_${now.millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  /// Export tasks to CSV and return the file path
  Future<String> exportToCsv(List<Task> tasks) async {
    final buffer = StringBuffer();
    buffer.writeln('Title,Description,Category,Priority,Status,Due Date,Created');

    for (final task in tasks) {
      final title = _escapeCsv(task.title);
      final desc = _escapeCsv(task.description);
      final status = task.isCompleted ? 'Completed' : 'Active';
      final priority = {1: 'Low', 2: 'Medium', 3: 'High'}[task.priority] ?? 'Medium';
      final dueDate = task.dueDate != null
          ? '${task.dueDate!.day}/${task.dueDate!.month}/${task.dueDate!.year}'
          : '';
      final created =
          '${task.createdAt.day}/${task.createdAt.month}/${task.createdAt.year}';

      buffer.writeln('$title,$desc,${task.category},$priority,$status,$dueDate,$created');
    }

    final dir = await getApplicationDocumentsDirectory();
    final now = DateTime.now();
    final file = File(
        '${dir.path}/focus24_export_${now.millisecondsSinceEpoch}.csv');
    await file.writeAsString(buffer.toString());
    return file.path;
  }

  /// Open a file
  Future<void> openFile(String path) async {
    await OpenFilex.open(path);
  }

  // ---------------------------------------------------------------------------
  // JSON backup / restore
  //
  // Categories are included only when the user has customized them
  // (userId != null). Built-in defaults are seeded from code on every fresh
  // install, so backing them up would create wasteful duplicate docs after
  // a restore.
  // ---------------------------------------------------------------------------

  // Bumped to v2 with the categories field. Restore still accepts v1 backups
  // — missing fields default to empty lists.
  static const int _backupSchemaVersion = 2;
  static const String _backupFilePrefix = 'focus24_backup_';

  /// Write a JSON snapshot of the user's data to app documents and return the
  /// file path. Includes a [_backupSchemaVersion] field so future restores can
  /// detect and migrate older formats.
  Future<String> exportBackupJson({
    required List<Task> tasks,
    required List<Project> projects,
    required List<Label> labels,
    required List<Note> notes,
    required List<TaskCategory> categories,
  }) async {
    final customCategories =
        categories.where((c) => c.userId != null).toList();
    final payload = <String, dynamic>{
      'schemaVersion': _backupSchemaVersion,
      'exportedAt': DateTime.now().toIso8601String(),
      'app': 'Focus24',
      'tasks': tasks.map((t) => t.toJson()).toList(),
      'projects': projects.map((p) => p.toJson()).toList(),
      'labels': labels.map((l) => l.toJson()).toList(),
      'notes': notes.map((n) => n.toJson()).toList(),
      'categories': customCategories.map((c) => c.toJson()).toList(),
    };
    final dir = await getApplicationDocumentsDirectory();
    final now = DateTime.now();
    final file =
        File('${dir.path}/$_backupFilePrefix${now.millisecondsSinceEpoch}.json');
    await file.writeAsString(jsonEncode(payload));
    return file.path;
  }

  /// List existing backup files in app documents, newest first.
  Future<List<File>> listBackups() async {
    final dir = await getApplicationDocumentsDirectory();
    final entities = dir.listSync().whereType<File>().where((f) {
      final name = f.uri.pathSegments.last;
      return name.startsWith(_backupFilePrefix) && name.endsWith('.json');
    }).toList();
    entities.sort((a, b) =>
        b.statSync().modified.compareTo(a.statSync().modified));
    return entities;
  }

  /// Append-only restore: every entity in the backup is added if its id is
  /// not already present locally. Existing entities are never overwritten,
  /// so a misaimed restore can't silently destroy data.
  ///
  /// Each entity is re-stamped with [userId] so a backup taken from a
  /// different account becomes the current user's data once imported.
  ///
  /// Order matters: projects/labels first, then tasks (which reference them
  /// by id), then notes. Returns per-collection counts.
  Future<RestoreResult> restoreFromBackupJson({
    required String path,
    required String userId,
    required Future<void> Function(Task) addTask,
    required Future<void> Function(Project) addProject,
    required Future<void> Function(Label) addLabel,
    required Future<void> Function(Note) addNote,
    required Future<void> Function(TaskCategory) addCategory,
    required Set<String> existingTaskIds,
    required Set<String> existingProjectIds,
    required Set<String> existingLabelIds,
    required Set<String> existingNoteIds,
    required Set<String> existingCategoryIds,
  }) async {
    final raw = await File(path).readAsString();
    final decoded = jsonDecode(raw);
    if (decoded is! Map<String, dynamic>) {
      throw const FormatException('Backup file is not a valid JSON object.');
    }
    final version = decoded['schemaVersion'];
    if (version is! int || version > _backupSchemaVersion) {
      throw FormatException(
        'Unsupported backup schemaVersion: $version. '
        'This app supports up to $_backupSchemaVersion.',
      );
    }

    final result = RestoreResult();

    // Categories first — tasks reference them by name, but having the icon/
    // color present beforehand means restored tasks render correctly the
    // moment they appear. Built-in default ids are also in
    // existingCategoryIds, so an old v1 backup that didn't filter defaults
    // out will skip them here.
    final categories = (decoded['categories'] as List?) ?? const [];
    for (final raw in categories) {
      final c = TaskCategory.fromJson(raw as Map<String, dynamic>);
      if (existingCategoryIds.contains(c.id)) {
        result.categoriesSkipped++;
        continue;
      }
      c.userId = userId;
      try {
        await addCategory(c);
        result.categoriesAdded++;
      } catch (_) {
        result.categoriesFailed++;
      }
    }

    final projects = (decoded['projects'] as List?) ?? const [];
    for (final raw in projects) {
      final p = Project.fromJson(raw as Map<String, dynamic>);
      if (existingProjectIds.contains(p.id)) {
        result.projectsSkipped++;
        continue;
      }
      p.userId = userId;
      try {
        await addProject(p);
        result.projectsAdded++;
      } catch (_) {
        result.projectsFailed++;
      }
    }

    final labels = (decoded['labels'] as List?) ?? const [];
    for (final raw in labels) {
      final l = Label.fromJson(raw as Map<String, dynamic>);
      if (existingLabelIds.contains(l.id)) {
        result.labelsSkipped++;
        continue;
      }
      l.userId = userId;
      try {
        await addLabel(l);
        result.labelsAdded++;
      } catch (_) {
        result.labelsFailed++;
      }
    }

    final tasks = (decoded['tasks'] as List?) ?? const [];
    for (final raw in tasks) {
      final t = Task.fromJson(raw as Map<String, dynamic>);
      if (existingTaskIds.contains(t.id)) {
        result.tasksSkipped++;
        continue;
      }
      t.userId = userId;
      // A backup from a different account would carry sharedListId/assigneeId
      // referring to lists/users the new account isn't a member of. Strip
      // those so the restored task lands as a personal task.
      final personal = t.copyWith(
        clearSharedList: true,
        clearAssignee: true,
      );
      try {
        await addTask(personal);
        result.tasksAdded++;
      } catch (_) {
        result.tasksFailed++;
      }
    }

    final notes = (decoded['notes'] as List?) ?? const [];
    for (final raw in notes) {
      final n = Note.fromJson(raw as Map<String, dynamic>);
      if (existingNoteIds.contains(n.id)) {
        result.notesSkipped++;
        continue;
      }
      n.userId = userId;
      try {
        await addNote(n);
        result.notesAdded++;
      } catch (_) {
        result.notesFailed++;
      }
    }

    return result;
  }

  pw.Widget _statBox(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        children: [
          pw.Text(value,
              style:
                  pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 2),
          pw.Text(label,
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  pw.Widget _taskRow(Task task, Map<int, String> priorityNames) {
    final priorityColor = {
      1: PdfColors.green,
      2: PdfColors.orange,
      3: PdfColors.red,
    };

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 4,
            height: 30,
            color: priorityColor[task.priority] ?? PdfColors.grey,
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  task.title,
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    decoration: task.isCompleted
                        ? pw.TextDecoration.lineThrough
                        : null,
                  ),
                ),
                if (task.description.isNotEmpty)
                  pw.Text(task.description,
                      style: const pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
                pw.SizedBox(height: 4),
                pw.Row(
                  children: [
                    pw.Text('${task.category}  ',
                        style: const pw.TextStyle(
                            fontSize: 9, color: PdfColors.grey600)),
                    pw.Text('${priorityNames[task.priority]}  ',
                        style: pw.TextStyle(
                            fontSize: 9,
                            color: priorityColor[task.priority] ??
                                PdfColors.grey)),
                    if (task.dueDate != null)
                      pw.Text(
                          'Due: ${task.dueDate!.day}/${task.dueDate!.month}/${task.dueDate!.year}',
                          style: const pw.TextStyle(
                              fontSize: 9, color: PdfColors.grey600)),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _escapeCsv(String value) {
    if (value.contains(',') || value.contains('"') || value.contains('\n')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }
}

class RestoreResult {
  int tasksAdded = 0, tasksSkipped = 0, tasksFailed = 0;
  int projectsAdded = 0, projectsSkipped = 0, projectsFailed = 0;
  int labelsAdded = 0, labelsSkipped = 0, labelsFailed = 0;
  int notesAdded = 0, notesSkipped = 0, notesFailed = 0;
  int categoriesAdded = 0, categoriesSkipped = 0, categoriesFailed = 0;

  int get totalAdded =>
      tasksAdded +
      projectsAdded +
      labelsAdded +
      notesAdded +
      categoriesAdded;
  int get totalSkipped =>
      tasksSkipped +
      projectsSkipped +
      labelsSkipped +
      notesSkipped +
      categoriesSkipped;
  int get totalFailed =>
      tasksFailed +
      projectsFailed +
      labelsFailed +
      notesFailed +
      categoriesFailed;

  String summary() {
    final parts = <String>[];
    if (tasksAdded > 0) parts.add('$tasksAdded tasks');
    if (projectsAdded > 0) parts.add('$projectsAdded projects');
    if (labelsAdded > 0) parts.add('$labelsAdded labels');
    if (notesAdded > 0) parts.add('$notesAdded notes');
    if (categoriesAdded > 0) parts.add('$categoriesAdded categories');
    final added = parts.isEmpty ? 'Nothing new' : 'Added ${parts.join(', ')}';
    final extras = <String>[];
    if (totalSkipped > 0) extras.add('$totalSkipped already present');
    if (totalFailed > 0) extras.add('$totalFailed failed');
    return extras.isEmpty ? added : '$added · ${extras.join(' · ')}';
  }
}
